using TEB.Core.Domain;
using TEB.Core.ViewModel;

namespace TEB.Core.Mapping
{
    public static class ProductMapping
    {
        public static Product ViewToModel(ProductViewModel model)
        {
            Product product = new Product
            {
                Id = model.Id,
                ProductTypeId = model.ProductTypeId,
                ParentGroupedProductId = model.ParentGroupedProductId,
                VisibleIndividually = model.VisibleIndividually,
                Name = model.Name,
                ShortDescription = model.ShortDescription,
                FullDescription = model.FullDescription,
                AdminComment = model.AdminComment,
                ProductTemplateId = model.ProductTemplateId,
                VendorId = model.VendorId,
                ShowOnHomePage = model.ShowOnHomePage,
                MetaKeywords = model.MetaKeywords,
                MetaDescription = model.MetaDescription,
                MetaTitle = model.MetaTitle,
                AllowCustomerReviews = model.AllowCustomerReviews,
                ApprovedRatingSum = model.ApprovedRatingSum,
                NotApprovedRatingSum = model.NotApprovedRatingSum,
                ApprovedTotalReviews = model.ApprovedTotalReviews,
                NotApprovedTotalReviews = model.NotApprovedTotalReviews,
                SubjectToAcl = model.SubjectToAcl,
                LimitedToStores = model.LimitedToStores,
                Sku = model.Sku,
                ManufacturerPartNumber = model.ManufacturerPartNumber,
                Gtin = model.Gtin,
                IsGiftCard = model.IsGiftCard,
                GiftCardTypeId = model.GiftCardTypeId,
                OverriddenGiftCardAmount = model.OverriddenGiftCardAmount,
                RequireOtherProducts = model.RequireOtherProducts,
                RequiredProductIds = model.RequiredProductIds,
                AutomaticallyAddRequiredProducts = model.AutomaticallyAddRequiredProducts,
                IsDownload = model.IsDownload,
                DownloadId = model.DownloadId,
                UnlimitedDownloads = model.UnlimitedDownloads,
                MaxNumberOfDownloads = model.MaxNumberOfDownloads,
                DownloadExpirationDays = model.DownloadExpirationDays,
                DownloadActivationTypeId = model.DownloadActivationTypeId,
                HasSampleDownload = model.HasSampleDownload,
                SampleDownloadId = model.SampleDownloadId,
                HasUserAgreement = model.HasUserAgreement,
                UserAgreementText = model.UserAgreementText,
                IsRecurring = model.IsRecurring,
                RecurringCycleLength = model.RecurringCycleLength,
                RecurringCyclePeriodId = model.RecurringCyclePeriodId,
                RecurringTotalCycles = model.RecurringTotalCycles,
                IsRental = model.IsRental,
                RentalPriceLength = model.RentalPriceLength,
                RentalPricePeriodId = model.RentalPricePeriodId,
                IsShipEnabled = model.IsShipEnabled,
                IsFreeShipping = model.IsFreeShipping,
                ShipSeparately = model.ShipSeparately,
                AdditionalShippingCharge = model.AdditionalShippingCharge,
                DeliveryDateId = model.DeliveryDateId,
                IsTaxExempt = model.IsTaxExempt,
                TaxCategoryId = model.TaxCategoryId,
                IsTelecommunicationsOrBroadcastingOrElectronicServices = model.IsTelecommunicationsOrBroadcastingOrElectronicServices,
                ManageInventoryMethodId = model.ManageInventoryMethodId,
                ProductAvailabilityRangeId = model.ProductAvailabilityRangeId,
                UseMultipleWarehouses = model.UseMultipleWarehouses,
                WarehouseId = model.WarehouseId,
                StockQuantity = model.StockQuantity,
                DisplayStockAvailability = model.DisplayStockAvailability,
                DisplayStockQuantity = model.DisplayStockQuantity,
                MinStockQuantity = model.MinStockQuantity,
                LowStockActivityId = model.LowStockActivityId,
                NotifyAdminForQuantityBelow = model.NotifyAdminForQuantityBelow,
                BackorderModeId = model.BackorderModeId,
                AllowBackInStockSubscriptions = model.AllowBackInStockSubscriptions,
                OrderMinimumQuantity = model.OrderMinimumQuantity,
                OrderMaximumQuantity = model.OrderMaximumQuantity,
                AllowedQuantities = model.AllowedQuantities,
                AllowAddingOnlyExistingAttributeCombinations = model.AllowAddingOnlyExistingAttributeCombinations,
                NotReturnable = model.NotReturnable,
                DisableBuyButton = model.DisableBuyButton,
                DisableWishlistButton = model.DisableWishlistButton,
                AvailableForPreOrder = model.AvailableForPreOrder,
                PreOrderAvailabilityStartDateTimeUtc = model.PreOrderAvailabilityStartDateTimeUtc,
                CallForPrice = model.CallForPrice,
                Price = model.Price,
                OldPrice = model.OldPrice,
                ProductCost = model.ProductCost,
                CustomerEntersPrice = model.CustomerEntersPrice,
                MinimumCustomerEnteredPrice = model.MinimumCustomerEnteredPrice,
                MaximumCustomerEnteredPrice = model.MaximumCustomerEnteredPrice,
                BasepriceEnabled = model.BasepriceEnabled,
                BasepriceAmount = model.BasepriceAmount,
                BasepriceUnitId = model.BasepriceUnitId,
                BasepriceBaseAmount = model.BasepriceBaseAmount,
                BasepriceBaseUnitId = model.BasepriceBaseUnitId,
                MarkAsNew = model.MarkAsNew,

                MarkAsNewStartDateTimeUtc = model.MarkAsNewStartDateTimeUtc,
                MarkAsNewEndDateTimeUtc = model.MarkAsNewEndDateTimeUtc,

                HasTierPrices = model.HasTierPrices,
                HasDiscountsApplied = model.HasDiscountsApplied,
                Weight = model.Weight,
                Length = model.Length,
                Width = model.Width,
                Height = model.Height,

                AvailableStartDateTimeUtc = model.AvailableStartDateTimeUtc,
                AvailableEndDateTimeUtc = model.AvailableEndDateTimeUtc,

                DisplayOrder = model.DisplayOrder,
                Published = model.Published,
                Deleted = model.Deleted
            };
            return product;
        }

        public static ProductViewModel ModelToView(Product model)
        {
            ProductViewModel product = new ProductViewModel
            {
                Id = model.Id,
                ProductTypeId = model.ProductTypeId,
                ParentGroupedProductId = model.ParentGroupedProductId,
                VisibleIndividually = model.VisibleIndividually,
                Name = model.Name,
                ShortDescription = model.ShortDescription,
                FullDescription = model.FullDescription,
                AdminComment = model.AdminComment,
                ProductTemplateId = model.ProductTemplateId,
                VendorId = model.VendorId,
                ShowOnHomePage = model.ShowOnHomePage,
                MetaKeywords = model.MetaKeywords,
                MetaDescription = model.MetaDescription,
                MetaTitle = model.MetaTitle,
                AllowCustomerReviews = model.AllowCustomerReviews,
                ApprovedRatingSum = model.ApprovedRatingSum,
                NotApprovedRatingSum = model.NotApprovedRatingSum,
                ApprovedTotalReviews = model.ApprovedTotalReviews,
                NotApprovedTotalReviews = model.NotApprovedTotalReviews,
                SubjectToAcl = model.SubjectToAcl,
                LimitedToStores = model.LimitedToStores,
                Sku = model.Sku,
                ManufacturerPartNumber = model.ManufacturerPartNumber,
                Gtin = model.Gtin,
                IsGiftCard = model.IsGiftCard,
                GiftCardTypeId = model.GiftCardTypeId,
                OverriddenGiftCardAmount = model.OverriddenGiftCardAmount,
                RequireOtherProducts = model.RequireOtherProducts,
                RequiredProductIds = model.RequiredProductIds,
                AutomaticallyAddRequiredProducts = model.AutomaticallyAddRequiredProducts,
                IsDownload = model.IsDownload,
                DownloadId = model.DownloadId,
                UnlimitedDownloads = model.UnlimitedDownloads,
                MaxNumberOfDownloads = model.MaxNumberOfDownloads,
                DownloadExpirationDays = model.DownloadExpirationDays,
                DownloadActivationTypeId = model.DownloadActivationTypeId,
                HasSampleDownload = model.HasSampleDownload,
                SampleDownloadId = model.SampleDownloadId,
                HasUserAgreement = model.HasUserAgreement,
                UserAgreementText = model.UserAgreementText,
                IsRecurring = model.IsRecurring,
                RecurringCycleLength = model.RecurringCycleLength,
                RecurringCyclePeriodId = model.RecurringCyclePeriodId,
                RecurringTotalCycles = model.RecurringTotalCycles,
                IsRental = model.IsRental,
                RentalPriceLength = model.RentalPriceLength,
                RentalPricePeriodId = model.RentalPricePeriodId,
                IsShipEnabled = model.IsShipEnabled,
                IsFreeShipping = model.IsFreeShipping,
                ShipSeparately = model.ShipSeparately,
                AdditionalShippingCharge = model.AdditionalShippingCharge,
                DeliveryDateId = model.DeliveryDateId,
                IsTaxExempt = model.IsTaxExempt,
                TaxCategoryId = model.TaxCategoryId,
                IsTelecommunicationsOrBroadcastingOrElectronicServices = model.IsTelecommunicationsOrBroadcastingOrElectronicServices,
                ManageInventoryMethodId = model.ManageInventoryMethodId,
                ProductAvailabilityRangeId = model.ProductAvailabilityRangeId,
                UseMultipleWarehouses = model.UseMultipleWarehouses,
                WarehouseId = model.WarehouseId,
                StockQuantity = model.StockQuantity,
                DisplayStockAvailability = model.DisplayStockAvailability,
                DisplayStockQuantity = model.DisplayStockQuantity,
                MinStockQuantity = model.MinStockQuantity,
                LowStockActivityId = model.LowStockActivityId,
                NotifyAdminForQuantityBelow = model.NotifyAdminForQuantityBelow,
                BackorderModeId = model.BackorderModeId,
                AllowBackInStockSubscriptions = model.AllowBackInStockSubscriptions,
                OrderMinimumQuantity = model.OrderMinimumQuantity,
                OrderMaximumQuantity = model.OrderMaximumQuantity,
                AllowedQuantities = model.AllowedQuantities,
                AllowAddingOnlyExistingAttributeCombinations = model.AllowAddingOnlyExistingAttributeCombinations,
                NotReturnable = model.NotReturnable,
                DisableBuyButton = model.DisableBuyButton,
                DisableWishlistButton = model.DisableWishlistButton,
                AvailableForPreOrder = model.AvailableForPreOrder,
                PreOrderAvailabilityStartDateTimeUtc = model.PreOrderAvailabilityStartDateTimeUtc,
                CallForPrice = model.CallForPrice,
                Price = model.Price,
                OldPrice = model.OldPrice,
                ProductCost = model.ProductCost,
                CustomerEntersPrice = model.CustomerEntersPrice,
                MinimumCustomerEnteredPrice = model.MinimumCustomerEnteredPrice,
                MaximumCustomerEnteredPrice = model.MaximumCustomerEnteredPrice,
                BasepriceEnabled = model.BasepriceEnabled,
                BasepriceAmount = model.BasepriceAmount,
                BasepriceUnitId = model.BasepriceUnitId,
                BasepriceBaseAmount = model.BasepriceBaseAmount,
                BasepriceBaseUnitId = model.BasepriceBaseUnitId,
                MarkAsNew = model.MarkAsNew,

                MarkAsNewStartDateTimeUtc = model.MarkAsNewStartDateTimeUtc,
                MarkAsNewEndDateTimeUtc = model.MarkAsNewEndDateTimeUtc,

                HasTierPrices = model.HasTierPrices,
                HasDiscountsApplied = model.HasDiscountsApplied,
                Weight = model.Weight,
                Length = model.Length,
                Width = model.Width,
                Height = model.Height,

                AvailableStartDateTimeUtc = model.AvailableStartDateTimeUtc,
                AvailableEndDateTimeUtc = model.AvailableEndDateTimeUtc,

                DisplayOrder = model.DisplayOrder,
                Published = model.Published,
                Deleted = model.Deleted
            };
            return product;
        }
    }
}
